package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"

	"github.com/meghraj/online-test-backend/internal/graph/generated"
	"github.com/meghraj/online-test-backend/internal/graph/model"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, email string, name string, password string) (*model.AuthPayload, error) {
	return r.AuthService.Register(ctx, email, name, password)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	if r == nil || r.Resolver == nil {
		return nil, gqlerror.Errorf("resolver not initialized")
	}
	if r.AuthService == nil {
		return nil, gqlerror.Errorf("AuthService is nil (not injected)")
	}
	return r.AuthService.Login(ctx, email, password) //delegate
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
