package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"

	"github.com/meghraj/online-test-backend/internal/graph/generated"
	"github.com/meghraj/online-test-backend/internal/graph/model"
)

// Register is the resolver for the register field.
// func (r *mutationResolver) Register(ctx context.Context, email string, name string, password string) (*model.AuthPayload, error) {
// 	hash, _ := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
// 	u := models.User{Email: email, Name: name, Role: models.RoleAdmin, PasswordHash: string(hash)}
// 	if err := m.DB.Create(&u).Error; err != nil {
// 		return nil, err
// 	}
// 	token, err := auth.Sign(u.ID.String(), string(u.Role))
// 	if err != nil {
// 		return nil, err
// 	}
// 	return &model.AuthPayload{
// 		AccessToken: token,
// 		User:        &model.User{ID: u.ID.String(), Email: u.Email, Name: u.Name, Role: model.Role(u.Role)},
// 	}, nil
// }

// Login is the resolver for the login field.
// func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
// 	var u models.User
// 	if err := m.DB.Where("email = ?", email).First(&u).Error; err != nil {
// 		return nil, fmt.Errorf("Invalid credentials")
// 	}
// 	if bcrypt.CompareHashAndPassword([]byte(u.PasswordHash), []byte(password)) != nil {
// 		return nil, fmt.Errorf("Invalid credential")
// 	}

// 	token, err := auth.Sign(u.ID.String(), string(u.Role))

// 	if err != nil {
// 		return nil, err
// 	}
// 	return &model.AuthPayload{
// 		AccessToken: token,
// 		User:        &model.User{ID: u.ID.String(), Email: u.Email, Name: u.Name, Role: model.Role(u.Role)},
// 	}, nil
// }

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
